default: &default
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: est

test:
  <<: *default
  database: est_test

production:
  <<: *default
  database: est
